# XcodeGen Project Definition
# This file is the single source of truth for the FilePilot Xcode project
# Generated .xcodeproj should NOT be committed to git
# Last Updated: 2025-11-04

name: FilePilot

options:
  bundleIdPrefix: com.jefahnierocks
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en
  createIntermediateGroups: true
  groupSortPosition: top
  indentWidth: 4
  tabWidth: 4
  usesTabs: false

settings:
  base:
    DEVELOPMENT_TEAM: "" # Set your team ID here or via env var
    PRODUCT_NAME: FilePilot
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.9
    MACOSX_DEPLOYMENT_TARGET: 14.0
    ENABLE_HARDENED_RUNTIME: YES
    COMBINE_HIDPI_IMAGES: YES

targets:
  FilePilot:
    type: application
    platform: macOS
    deploymentTarget: "14.0"

    sources:
      - path: FilePilot
        excludes:
          - "FilePilot/**"  # Exclude nested folder
          - "*.bak"
          - ".build"
          - ".swiftpm"
          - "Package.swift"
          - "FilePilotTests"
          - "FilePilotUITests"

    settings:
      base:
        INFOPLIST_FILE: FilePilot/Info.plist
        CODE_SIGN_ENTITLEMENTS: FilePilot/FilePilot.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.jefahnierocks.FilePilot
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_HARDENED_RUNTIME: YES
        SWIFT_VERSION: 5.9

    dependencies: []
      # Add SPM dependencies here as needed
      # Example: - package: SwiftGit2

    scheme:
      testTargets:
        - FilePilotTests
      gatherCoverageData: true
      coverageTargets:
        - FilePilot

  FilePilotTests:
    type: bundle.unit-test
    platform: macOS

    sources:
      - FilePilot/FilePilotTests

    dependencies:
      - target: FilePilot

    settings:
      base:
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/FilePilot.app/Contents/MacOS/FilePilot
        SWIFT_VERSION: 5.9
        GENERATE_INFOPLIST_FILE: YES

  FilePilotUITests:
    type: bundle.ui-testing
    platform: macOS

    sources:
      - FilePilot/FilePilotUITests

    dependencies:
      - target: FilePilot

    settings:
      base:
        TEST_TARGET_NAME: FilePilot
        SWIFT_VERSION: 5.9
        GENERATE_INFOPLIST_FILE: YES

schemes:
  FilePilot:
    build:
      targets:
        FilePilot: all
        FilePilotTests: [test]
        FilePilotUITests: [test]

    run:
      config: Debug
      commandLineArguments:
        "--enable-telemetry": true
      environmentVariables:
        - variable: TELEMETRY_ENDPOINT
          value: http://localhost:3000/api/swift/telemetry
          isEnabled: true

    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - FilePilot
      targets:
        - name: FilePilotTests
          parallelizable: true
          randomExecutionOrder: true

    archive:
      config: Release
